### ISSUE TITLE
실전 알고리즘 문제집 풀이 집단 지성 프로젝트 참여를 부탁드립니다,,,

### ISSUE THREAD

**Issue by encrypted-def** [EndlessCreation/ddul_a_bboung_2021#7]
여기 이렇게 Issue를 남겨도 될지 모르겠네요

제 자료들이 뚫어뻥 스터디 멤버분들(?)에게 어째 도움이 되시는 것 같아 다행입니다.

제가 연습문제로 올려둔 문제들을 스터디에서 같이 푸시는 것 같은데, 혹시 [여기](https://github.com/encrypted-def/basic-algo-lecture/blob/master/solution-request.md)에 코드를 기여해주신다면 양질의 자료를 만드는데 도움이 될 것 같습니다.

스터디 화이팅하시고 문제를 풀다가 코드가 마음에 들면 제 repository에도 기여해주신다면 감사하겠습니다!

**Comment by DNATUNA** [comment]
@encrypted-def 늦게 확인하여 죄송합니다..! 현재 학교 시험 기간이여 잠시 스터디를 쉬고 있습니다. 다시 스터디가 시작되면 바킹독님의 
📡문제집 풀이 집단 지성 프로젝트📡에 참여해보겠습니다! 아직 초보자들이지만 열심히 공부해서 도움이 될 수 있도록 노력할게요^^

**Comment by encrypted-def** [comment]
앗 그렇군여 감사합니다 시험 잘 치세요!!
